### ISSUE TITLE
增加主题后编译报错[两台电脑有一台报错，另一台成功]

### ISSUE THREAD

**Issue by bart1989** [vuepress-reco/vuepress-theme-reco#105]
开始怀疑与环境有关系。我把报错电脑的node版本、vue版本、vuepress版本都确认为不报错的电脑一致后还是不行。

found in

---> <NavLink>
       <NavLinks>
         <Navbar>
           <Common>
             <Anonymous>
               <Anonymous>
                 <Root>
error Error rendering /: false
undefined
TypeError: Cannot read property 'match' of undefined
    at ensureExt (node_modules/vuepress-theme-reco/util/index.js:35:0)
    at Proxy.link (node_modules/vuepress-theme-reco/components/NavLink.vue:35:0)
    at Proxy.computedGetter (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue/dist/vue.runtime.common.dev.js:4825:15)
    at Proxy.render (node_modules/vuepress-theme-reco/components/NavLink.vue?e84c:1:89)
    at VueComponent.Vue._render (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue/dist/vue.runtime.common.dev.js:3532:22)
    at resolve (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:8400:27)
    at waitForServerPrefetch (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at renderComponentInner (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:8411:3)
    at renderComponent (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at RenderContext.renderNode (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:8279:5)
    at RenderContext.next (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:2598:23)
    at cachedWrite (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:2451:9)
    at renderStringNode$1 (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:8496:5)
    at RenderContext.renderNode (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:8277:5)
    at RenderContext.next (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:2598:23)
    at RenderContext.cachedWrite [as write] (/Users/apple/Documents/VueWorkspace/BTLBlog/node_modules/vue-server-renderer/build.dev.js:2451:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by H-TWINKLE** [comment]
应该怎么解决呀

**Comment by wuhou123** [comment]
已收到，谢谢

**Comment by recoluan** [comment]
建议升级2.0吧，1.0不维护了
