### ISSUE TITLE
热更新报错

### ISSUE THREAD

**Issue by danielmlc** [vuepress-reco/vuepress-theme-reco#124]
## Bug report
```
error @vuepress/plugin-blog apply clientDynamicModules failed.
(node:13336) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reduce' of undefined
    at clientDynamicModules (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_plugin-blog@1.3.0@@vuepress\plugin-blog\lib\node\index.js:88:81)
    at ClientDynamicModulesOption.asyncApply (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_core@1.3.0@@vuepress\core\lib\node\plugin-api\abstract\AsyncOption.js:33:21)
    at async ClientDynamicModulesOption.apply (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_core@1.3.0@@vuepress\core\lib\node\plugin-api\override\ClientDynamicModulesOption.js:15:5)
    at async PluginAPI.applyAsyncOption (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_core@1.3.0@@vuepress\core\lib\node\plugin-api\index.js:277:5)
    at async Promise.all (index 0)
    at async App.process (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_core@1.3.0@@vuepress\core\lib\node\App.js:124:5)
(node:13336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error @vuepress/plugin-blog apply clientDynamicModules failed.
(node:13336) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reduce' of undefined
    at clientDynamicModules (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_plugin-blog@1.3.0@@vuepress\plugin-blog\lib\node\index.js:88:81)
    at ClientDynamicModulesOption.asyncApply (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_core@1.3.0@@vuepress\core\lib\node\plugin-api\abstract\AsyncOption.js:33:21)
    at async ClientDynamicModulesOption.apply (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_core@1.3.0@@vuepress\core\lib\node\plugin-api\override\ClientDynamicModulesOption.js:15:5)
    at async PluginAPI.applyAsyncOption (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_core@1.3.0@@vuepress\core\lib\node\plugin-api\index.js:277:5)
    at async Promise.all (index 0)
    at async App.process (e:\我的项目\一些网站\vuepress\danielmlc-blog\node_modules\_@vuepress_core@1.3.0@@vuepress\core\lib\node\App.js:124:5)
(node:13336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
warning Override existing page /tag/.
warning Override existing page /categories/.
warning Override existing page /timeline/.


```
#### Other relevant information

```
  "vuepress": "1.2.0",
  "vuepress-theme-reco": "1.2.0-alpha.15",
```

**Comment by recoluan** [comment]
1. 你在项目中使用 @vuepress/plugin-blog 这个插件了吗，如果使用了去掉，因为主题已经内了；
2. 主题升级到最新版本 1.2.2 试一下。

**Comment by danielmlc** [comment]
按照你说的改了也不行








--退笔如山未足珍，读书万卷始通神。



在 2020-02-04 16:05:08，"reco_luan" <notifications@github.com> 写道：

你在项目中使用 @vuepress/plugin-blog 这个插件了吗，如果使用了去掉，因为主题已经内了；
主题升级到最新版本 1.2.2 试一下。

**Comment by recoluan** [comment]
我把你的博客下载下来试了一下，没问题的啊

**Comment by danielmlc** [comment]
是不是我的环境问题  我的node是v12.14.1

**Comment by danielmlc** [comment]
第一次打包没问题 当修改了config.js文件热更新的时候就报错了

**Comment by danielmlc** [comment]
@recoluan  还有个诡异的问题 我按照你的手动部署教程部署到gh-pages分支样式全丢了

![image](https://user-images.githubusercontent.com/16604995/73745501-229f1300-478e-11ea-97c2-de2e86abb698.png)

**Comment by ZUOZHE1997** [comment]
我也是啊,但是我在打包时静态资源没有加载出来,样式也丢了,找了好久的问题,路径都重新设置了一遍,本地运行是没事的,

**Comment by recoluan** [comment]
> @recoluan 还有个诡异的问题 我按照你的手动部署教程部署到gh-pages分支样式全丢了
> 
> ![image](https://user-images.githubusercontent.com/16604995/73745501-229f1300-478e-11ea-97c2-de2e86abb698.png)

因为部署的位置不是域名的根目录，需要设置 base，详情请见 vuepress 官网。

**Comment by willtfn** [comment]
所以热更新报错的问题怎么处理的？是node版本问题吗？
