### ISSUE TITLE
默认配置下构建出错

### ISSUE THREAD

**Issue by stevapple** [vuepress-reco/vuepress-theme-reco#150]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

`vuepress dev` 和 `vuepress build` 出现 warning：

```
warning An error was encountered in plugin "@vuepress-reco/back-to-top"
warning An error was encountered in plugin "@vuepress-reco/extract-code"
warning An error was encountered in plugin "@vuepress-reco/loading-page"
warning An error was encountered in plugin "@vuepress-reco/pagation"
warning An error was encountered in plugin "@vuepress-reco/comments"
warning An error was encountered in plugin "@vuepress/medium-zoom"
warning An error was encountered in plugin "@vuepress/plugin-blog"
```

`vuepress build` 失败：

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'list' of undefined"

found in

---> <PersonalInfo>
       <Sidebar>
         <Common>
           <Anonymous>
             <GlobalLayout>
               <Root>
error Error rendering /: false
undefined
TypeError: Cannot read property 'list' of undefined
    at Proxy.$recoPosts (node_modules/vuepress-theme-reco/mixins/posts.js:7:23)
    at Proxy.computedGetter (/Users/stevapple/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.dev.js:4831:15)
    at Proxy.render (node_modules/vuepress-theme-reco/components/PersonalInfo.vue?597a:1:142)
    at VueComponent.Vue._render (/Users/stevapple/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
    at resolve (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8415:27)
    at waitForServerPrefetch (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8287:3)
    at renderComponentInner (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8426:3)
    at renderComponent (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8383:5)
    at RenderContext.renderNode (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8294:5)
    at RenderContext.next (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:2598:23)
    at cachedWrite (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:2451:9)
    at renderElement (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8544:5)
    at renderNode (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8296:5)
    at resolve (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8421:5)
    at waitForServerPrefetch (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8287:3)
    at renderComponentInner (/Users/stevapple/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8426:3)
```

`vuepress dev` 前端五处报错：

```
[Vue warn]: Unknown custom element: <LoadingPage> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Common> at node_modules/vuepress-theme-reco/components/Common.vue
       <Layout> at node_modules/vuepress-theme-reco/layouts/Layout.vue
         <GlobalLayout> at .config/yarn/global/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
           <Root>
```

```
[Vue warn]: Error in render: "TypeError: undefined is not an object (evaluating 'this.$categories.list')"

found in

---> <PersonalInfo> at node_modules/vuepress-theme-reco/components/PersonalInfo.vue
       <Sidebar> at node_modules/vuepress-theme-reco/components/Sidebar.vue
         <Common> at node_modules/vuepress-theme-reco/components/Common.vue
           <Layout> at node_modules/vuepress-theme-reco/layouts/Layout.vue
             <GlobalLayout> at .config/yarn/global/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
               <Root>
```

```
TypeError: undefined is not an object (evaluating 'this.$categories.list')
```

```
[Vue warn]: Unknown custom element: <AccessNumber> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Footer> at node_modules/vuepress-theme-reco/components/Footer.vue
       <Common> at node_modules/vuepress-theme-reco/components/Common.vue
         <Layout> at node_modules/vuepress-theme-reco/layouts/Layout.vue
           <GlobalLayout> at .config/yarn/global/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
             <Root>
```

```
[Vue warn]: Unknown custom element: <Comments> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Common> at node_modules/vuepress-theme-reco/components/Common.vue
       <Layout> at node_modules/vuepress-theme-reco/layouts/Layout.vue
         <GlobalLayout> at .config/yarn/global/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
           <Root>
```

#### Other relevant information

- Your OS: macOS 10.15.4
- Node.js version: v13.11.0
- VuePress version:  1.4.0
- VuePress-theme-reco version: 1.3.2
- Which package manager did you use for the install(npm/cnpm/yarn)? npm and yarn, both have the same output

**Comment by recoluan** [comment]
This problem shows that the packages was not installed correctly. Please remove the 'node_modules' folder to reinstall the packages.

**Comment by stevapple** [comment]
Have already tried more than twice, with both `yarn` and `npm`.

**Comment by stevapple** [comment]
I believe it to be a bug of either vuepress or reco, it seems more likely a reco one.

**Comment by stevapple** [comment]
Here is the `yarn.lock` file. 

[yarn.lock.zip](https://github.com/vuepress-reco/vuepress-theme-reco/files/4401580/yarn.lock.zip)

**Comment by recoluan** [comment]
Personally, I have encountered the same problem as you.

I have three projects that rely on `vuepress-theme-reco`, and one of them, like in your case, cannot find a package in `vuepress-theme-reco`. Local is fine, but gitlab's ci will have problems like yours, and clearing ci's cache won't work. But one day there was nothing wrong with it.

Some friends also encountered the same problem, the reinstallation solved some friends' problems.If reinstallation does not solve your problem, I am sorry that I cannot give the correct explanation according to my understanding at present.

If you find a solution, welcome back and explain.

**Comment by stevapple** [comment]
Can it be a problem with the npm registry? I’m using a mirror as npmjs.org is too slow.

**Comment by stevapple** [comment]
I've tested that, and the result is not. 

Have you tested with nodejs 13.11.0 and vuepress 1.4.0? I cannot get it work in Ubuntu either. Looks like nothing to do with macOS.

**Comment by stevapple** [comment]
@recoluan Problem solved, here's the solution: [https://blog.csdn.net/zpfz756/article/details/104233938](https://blog.csdn.net/zpfz756/article/details/104233938). 

It seems a bug of vuepress itself, and you may add the solution to the document (FAQ or as a warning box) since the latest vuepress hasn't fixed it yet?

**Comment by recoluan** [comment]
I did it the same way, but it felt a bit far-fetched. Still, it should be described in the FAQ. Thank you very much.

**Comment by anprettyboy** [comment]
解决了吗 @recoluan 
have you solved this problem? @stevapple
