### ISSUE TITLE
Error: Cannot find module "..../public/manifest/client.json"

### ISSUE THREAD

**Issue by mhy-web** [vuepress-reco/vuepress-theme-reco#166]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
执行 npm  run build时报错，public/manifest 目录下只生成了server.json，没有client.json
```
Error: Cannot find module '/Users/mhy/private/blog-vuepress/public/manifest/client.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Build.render (/Users/mhy/private/blog-vuepress/node_modules/@vuepress/core/lib/node/build/index.js:56:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### Other relevant information

- Your OS:  mac os 10.14.5
- Node.js version:  v10.15.3
- VuePress version:  1.3.1
- VuePress-theme-reco version: 1.3.2
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by recoluan** [comment]
你都用了什么插件啊，估计是某个插件需要你提供 `/public/manifest/client.json` 这么一个文件吧，是不是那个 PWA 插件，主题本身没有对这个文件的依赖。

**Comment by mhy-web** [comment]
在mac上，我关掉所有插件然后打包，依然有这个报错，但是在windows的wsl上可以打包。

在wsl上有另外一个问题，每次配置文件或者文章的yaml配置有改动，终端编译完之后浏览器刷新依然有一堆报错，必须得重新npm run dev才可以

**Comment by mhy-web** [comment]
mac打包问题解决了，原因是我的mac的环境变量里默认NODE_ENV=development，打包的时候必须设置为production
