### ISSUE TITLE
TypeError: Cannot destructure property 'currentRoute' of 'Qe(...)' as it is undefined.

### ISSUE THREAD

**Issue by shichaohui** [vuepress-reco/vuepress-theme-reco#172]
## Bug report

TypeError: Cannot destructure property 'currentRoute' of 'Qe(...)' as it is undefined.

#### What is actually happening?

```
TypeError: Cannot destructure property 'currentRoute' of 'Qe(...)' as it is undefined.      framework-8abcb967.js:1 
    at M2 (/blog/assets/app-c4bf64b9.js:53:23132)
    at Xq2 (/blog/assets/app-c4bf64b9.js:58:1263927)
    at Object.setup (/blog/assets/app-c4bf64b9.js:64:56652)
    at setup (/blog/assets/app-c4bf64b9.js:64:91790)
    at rt (/blog/assets/framework-8abcb967.js:1:13228)
    at gc (/blog/assets/framework-8abcb967.js:1:53769)
    at pc (/blog/assets/framework-8abcb967.js:1:53554)
    at L (/blog/assets/framework-8abcb967.js:1:43148)
    at h (/blog/assets/framework-8abcb967.js:1:37547)
    at f (/blog/assets/framework-8abcb967.js:1:36660)
Hydration completed but contains mismatches.                   framework-8abcb967.js:1 
```

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v18.15.0
- VuePress version: 2.0.0-beta.61
- VuePress-theme-reco version: 2.0.0-beta.55
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? yarn

**Comment by shichaohui** [comment]
It is ok, when I delete `yarn.lock` and regenerate it.
