### ISSUE TITLE
npm run build： Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by HiEdison** [vuepress-reco/vuepress-theme-reco#179]
我的项目是提交到gitee中的，
在文档中我引用了图片，
`![](../../_assets/Pasted%20image%2020230424143008.png)`
在obsidian和gitee中能显示
但是使用 npm run build `打包就会出错，无法处理  ``![]()``  这种格式问题。

Error: Failed to compile with errors.
    at D:\Developer\Gitee\obsidain-blog\node_modules\@vuepress\core\lib\node\build\index.js:190:16
    at finalCallback (D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\MultiCompiler.js:277:6
    at done (D:\Developer\Gitee\obsidain-blog\node_modules\neo-async\async.js:2931:13)
    at runCompilers (D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\MultiCompiler.js:181:48)
    at D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\MultiCompiler.js:188:7
    at D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\MultiCompiler.js:270:7
    at finalCallback (D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\Compiler.js:257:39)
    at D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\Hook.js:154:20)
    at onCompiled (D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\Compiler.js:271:21)
    at D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\Hook.js:154:20)
    at D:\Developer\Gitee\obsidain-blog\node_modules\webpack\lib\Compilation.js:1414:32
    at eval (eval at create (D:\Developer\Gitee\obsidain-blog\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:17:1)
    at D:\Developer\Gitee\obsidain-blog\node_modules\terser-webpack-plugin\dist\index.js:321:9
    at step (D:\Developer\Gitee\obsidain-blog\node_modules\terser-webpack-plugin\dist\TaskRunner.js:87:9)
    at done (D:\Developer\Gitee\obsidain-blog\node_modules\terser-webpack-plugin\dist\TaskRunner.js:98:30)
    at tryCatcher (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._settlePromise (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:617:21)
    at Promise._settlePromise0 (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:489:14)
    at Promise._settlePromiseFromHandler (D:\Developer\Gitee\obsidain-blog\node_modules\bluebird\js\release\promise.js:559:17)

**Comment by recoluan** [comment]
这是编译 bug，算是 vuepress 的 bug 了，这里只是主题。

**Comment by HiEdison** [comment]
![](../../_assets/Pasted%20image%2020230424143008.png)  这个错误问题，我已经知道原因，
其中%20是空格，只要确保图片路径中没有空格， npm run build 将正确通过，同时在网页上也能看到图片
