### ISSUE TITLE
dev 正常 build 下报错

### ISSUE THREAD

**Issue by GPPoseidon999** [vuepress-reco/vuepress-theme-reco#185]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
```
TypeError: Cannot read property 'match' of undefined
    at ensureExt (node_modules/vuepress-theme-reco/helpers/utils.js:35:25)
    at Proxy.link (node_modules/vuepress-theme-reco/components/NavLink.vue:35:0)
    at Proxy.computedGetter (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue/dist/vue.runtime.common.dev.js:4831:15)
    at Proxy.render (node_modules/vuepress-theme-reco/components/NavLink.vue?fbf7:1:89)
    at VueComponent.Vue._render (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
    at resolve (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:8415:27)
    at waitForServerPrefetch (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:8287:3)
    at renderComponentInner (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:8426:3)
    at renderComponent (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:8383:5)
    at RenderContext.renderNode (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:8294:5)
    at RenderContext.next (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:2598:23)
    at cachedWrite (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:2451:9)
    at renderStringNode$1 (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:8511:5)
    at RenderContext.renderNode (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:8292:5)
    at RenderContext.next (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:2598:23)
    at RenderContext.cachedWrite [as write] (/Users/yupengfei/Desktop/project/singleshadow.io/node_modules/vue-server-renderer/build.dev.js:2451:9)
```

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 
- VuePress-theme-reco version: 
- Which package manager did you use for the install(npm/cnpm/yarn)?

**Comment by GPPoseidon999** [comment]
NavLink  item值在初始化没有文章情况下没有link属性
