### ISSUE TITLE
rss build 

### ISSUE THREAD

**Issue by wkii** [vuepress-reco/vuepress-theme-reco#186]
#10  Bug report
@vuepress-reco/vuepress-plugin-rss 
version: 1.0.1
build error:
```
error @vuepress-reco/vuepress-plugin-rss apply generated failed.
TypeError: item.categories.forEach is not a function
    at /Users/terry/Sites/vueblog/node_modules/rss/lib/index.js:71:25
    at Array.forEach (<anonymous>)
    at generateXML (/Users/terry/Sites/vueblog/node_modules/rss/lib/index.js:63:16)
    at RSS.xml (/Users/terry/Sites/vueblog/node_modules/rss/lib/index.js:185:17)
    at generated (/Users/terry/Sites/vueblog/node_modules/@vuepress-reco/vuepress-plugin-rss/index.js:46:14)
    at AsyncOption.asyncApply (/Users/terry/Sites/vueblog/node_modules/@vuepress/core/lib/node/plugin-api/abstract/AsyncOption.js:33:21)
    at PluginAPI.applyAsyncOption (/Users/terry/Sites/vueblog/node_modules/@vuepress/core/lib/node/plugin-api/index.js:277:32)
    at Build.render (/Users/terry/Sites/vueblog/node_modules/@vuepress/core/lib/node/build/index.js:101:34)
    at async App.build (/Users/terry/Sites/vueblog/node_modules/@vuepress/core/lib/node/App.js:499:5)
error Command failed with exit code 1.
```
- Your OS: macos
- Node.js version: v13.13.0
- VuePress version: vuepress/1.5.0
- VuePress-theme-reco version:  1.4.5
- Which package manager did you use for the install(npm/cnpm/yarn)? 
yarn

**Comment by recoluan** [comment]
请升级至 `vuepress-plugin-rss@1.0.2`。
