### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by microseyuyu** [vuepress-reco/vuepress-theme-reco#225]
## Bug report

vuepress build error with @vuepress/theme-default:  2.0.0-beta.66 (2.0.0-beta.45)

#### What is actually happening?

I try to build it and then goes:

```
➜  microseyuyu-wiki-test sudo npm run build

> vuepress-theme-reco-demo@2.0.0 build
> vuepress build .

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/microseyuyu/microseyuyu-wiki-test/node_modules/vuepress/lib/index.js from /Users/microseyuyu/microseyuyu-wiki-test/.vuepress/config.ts not supported.
Instead change the require of index.js in /Users/microseyuyu/microseyuyu-wiki-test/.vuepress/config.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/microseyuyu/microseyuyu-wiki-test/.vuepress/config.ts:29:23)
    at require.extensions..ts (/Users/microseyuyu/microseyuyu-wiki-test/node_modules/vuepress-webpack/node_modules/@vuepress/cli/lib/utils/allowTs.js:11:11)
    at loadUserConfigCjs (/Users/microseyuyu/microseyuyu-wiki-test/node_modules/vuepress-webpack/node_modules/@vuepress/cli/lib/config/loadUserConfigCjs.js:9:22)
    at loadUserConfig (/Users/microseyuyu/microseyuyu-wiki-test/node_modules/vuepress-webpack/node_modules/@vuepress/cli/lib/config/loadUserConfig.js:16:20)
    at /Users/microseyuyu/microseyuyu-wiki-test/node_modules/vuepress-webpack/node_modules/@vuepress/cli/lib/commands/build/createBuild.js:21:58
    at CAC.wrappedCommand (/Users/microseyuyu/microseyuyu-wiki-test/node_modules/vuepress-webpack/node_modules/@vuepress/cli/lib/cli.js:12:41)
    at CAC.runMatchedCommand (/Users/microseyuyu/microseyuyu-wiki-test/node_modules/cac/dist/index.js:614:34)
    at CAC.parse (/Users/microseyuyu/microseyuyu-wiki-test/node_modules/cac/dist/index.js:541:12)
    at cli (/Users/microseyuyu/microseyuyu-wiki-test/node_modules/vuepress-webpack/node_modules/@vuepress/cli/lib/cli.js:61:13)
    at Object.<anonymous> (/Users/microseyuyu/microseyuyu-wiki-test/node_modules/vuepress-webpack/bin/vuepress.js:8:1)
#### Other relevant information
```

That's all the log

- Your OS: macOS 13.4.1
- Node.js version: 20.5.0
- VuePress version: 2.0.0-beta.66
- VuePress-theme-reco version: 2.0.0-beta.66
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)?
yarn & npm

**Comment by recoluan** [comment]
It's not a bug of theme reco.
