### ISSUE TITLE
Error when Handling the Character `|` in the Cell of Table

### ISSUE THREAD

**Issue by gitDebuger** [vuepress-reco/vuepress-theme-reco#309]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

When compiling a markdown file like this one:

```markdown
# A Test File

| non-terminal\terminal |                         `IDENFR`                          | `ELSETK` | `INTTK` | `CHARTK` |
| :-------------: | :-------------------------------------------------------: | :------: | :-----: | :------: |
|  `<UnaryExp>`   | `<PrimaryExp> | IDENFR LPARENT <FuncRParamsList> RPARENT` |          |         |          |
|    `<Stmt>`     |                             √                             |          |         |          |
|   `<ElseOpt>`   |                                                           |    √     |         |          |
|  `<DeclList>`   |                                                           |          |    √    |    √     |
| `<FuncDefList>` |                                                           |          |    √    |          |
```

Vite will throw an error:

```powershell
[vite:vue] [plugin vite:vue] .vuepress/.temp/pages/blogs/test/Test.html.vue (15:32): Element is missing end tag.
file: D:/Myself/reco/.vuepress/.temp/pages/blogs/test/Test.html.vue:15:32
SyntaxError: [plugin vite:vue] .vuepress/.temp/pages/blogs/test/Test.html.vue (15:32): Element is missing end tag.
    at createCompilerError (D:\Myself\reco\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1359:17)
    at emitError (D:\Myself\reco\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2911:5)
    at Object.onclosetag (D:\Myself\reco\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2303:13)
    at Tokenizer.stateInClosingTagName (D:\Myself\reco\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:784:16)
    at Tokenizer.parse (D:\Myself\reco\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1142:16)
    at Object.baseParse (D:\Myself\reco\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2943:13)
    at Object.parse (D:\Myself\reco\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.prod.js:662:23)
    at Object.parse$2 [as parse] (D:\Myself\reco\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1790:24)
    at createDescriptor (file:///D:/Myself/reco/node_modules/@vitejs/plugin-vue/dist/index.mjs:64:43)
    at transformMain (file:///D:/Myself/reco/node_modules/@vitejs/plugin-vue/dist/index.mjs:2405:34)
```

But this file should be displayed like this:

![Display](https://github.com/user-attachments/assets/f846c4c1-e3fc-4e44-a127-fc9f86026ed2)

When we check the temporary Vue file, we can see codes causing this error:

```vue
<tr>
<td style="text-align:center"><code v-pre>&lt;UnaryExp&gt;</code></td>
<td style="text-align:center">`<PrimaryExp></td>
<td style="text-align:center">IDENFR LPARENT <FuncRParamsList> RPARENT`</td>
<td style="text-align:center"></td>
<td style="text-align:center"></td>
</tr>
```

Just say, the character `|` in the content of the cell is be treated as divider between cells of the table.

#### Other relevant information

- Your OS: Windows
- Node.js version: `v20.11.0`
- VuePress version: `^2.0.0-rc.15`
- VuePress-theme-reco version: `2.0.0-rc.18`
- Which package manager did you use for the install(npm/cnpm/yarn/pnpm)? `npm`

**Comment by recoluan** [comment]
Please replace `<PrimaryExp> | IDENFR LPARENT <FuncRParamsList> RPARENT` to  `<PrimaryExp> \| IDENFR LPARENT <FuncRParamsList> RPARENT`. Because `|` will be interpreted as `<td>`.


**Good Case:**
```markdown
# A Test File

| non-terminal\terminal |                         `IDENFR`                          | `ELSETK` | `INTTK` | `CHARTK` |
| :-------------: | :-------------------------------------------------------: | :------: | :-----: | :------: |
|  `<UnaryExp>`   | `<PrimaryExp> \| IDENFR LPARENT <FuncRParamsList> RPARENT` |          |         |          |
|    `<Stmt>`     |                             √                             |          |         |          |
|   `<ElseOpt>`   |                                                           |    √     |         |          |
|  `<DeclList>`   |                                                           |          |    √    |    √     |
| `<FuncDefList>` |                                                           |          |    √    |          |
```

![image](https://github.com/user-attachments/assets/8c1fcb8c-86ba-4037-9200-d7e445f69a62)
