### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by ybGo** [vuepress-reco/vuepress-theme-reco#360]
Cannot resolve theme: reco
at resolveTheme (/Users/yb/.config/yarn/global/node_modules/@vuepress/core/lib/node/loadTheme.js:111:13)
at loadTheme (/Users/yb/.config/yarn/global/node_modules/@vuepress/core/lib/node/loadTheme.js:36:17)
at App.process (/Users/yb/.config/yarn/global/node_modules/@vuepress/core/lib/node/App.js:105:21)
at processTicksAndRejections (node:internal/process/task_queues:94:5)
at async dev (/Users/yb/.config/yarn/global/node_modules/@vuepress/core/lib/index.js:17:3)

请问 这是什么问题

**Comment by ybGo** [comment]
npm run dev报错， 新手求助

**Comment by wencwcoder** [comment]
@ybGo 这是不是没有安装依赖呀
