### ISSUE TITLE
[2.x]build出问题

### ISSUE THREAD

**Issue by googidaddy** [vuepress-reco/vuepress-theme-reco#58]
```
moduleIdentifier: "/Users/sicko/blog/test-blog/sicko's blog/.vuepress/.temp/internal/clientAppEnhances.js",
  moduleName: './.vuepress/.temp/internal/clientAppEnhances.js',
  loc: '1:65',
  message: 'Module parse failed: Unexpected token (1:65)\n' +
    'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
    "> import clientAppEnhance0 from '/Users/sicko/blog/test-blog/sicko's blog/node_modules/@vuepress/plugin-theme-data/lib/client/clientAppEnhance.js'\n" +
    "| import clientAppEnhance1 from '/Users/sicko/blog/test-blog/sicko's blog/node_modules/@vuepress/plugin-search/lib/client/clientAppEnhance.js'\n" +
    "| import clientAppEnhance2 from '/Users/sicko/blog/test-blog/sicko's blog/node_modules/@vuepress/plugin-external-link-icon/lib/client/clientAppEnhance.js'",
```
`Error: Failed to compile with errors
    at /Users/sicko/blog/test-blog/sicko's blog/node_modules/@vuepress/bundler-webpack/lib/build/createBuild.js:37:28
    at /Users/sicko/blog/test-blog/sicko's blog/node_modules/webpack/lib/webpack.js:148:8
    at /Users/sicko/blog/test-blog/sicko's blog/node_modules/neo-async/async.js:2830:7
    at done (/Users/sicko/blog/test-blog/sicko's blog/node_modules/neo-async/async.js:2865:11)
    at /Users/sicko/blog/test-blog/sicko's blog/node_modules/neo-async/async.js:2818:7
    at /Users/sicko/blog/test-blog/sicko's blog/node_modules/webpack/lib/HookWebpackError.js:68:3
    at _done (eval at create (/Users/sicko/blog/test-blog/sicko's blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/sicko/blog/test-blog/sicko's blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)`
似乎没解决这个问题，版本均是最新的。

**Comment by googidaddy** [comment]
已更新最新的0.8版本，本地是正常的，build的时候报错显示window is not defined.
`ReferenceError: window is not defined
    at /Users/sicko/blog/test/.vuepress/.temp/.server/app.js:24358:9
    at /Users/sicko/blog/test/.vuepress/.temp/.server/app.js:24355:44
    at e.exports (/Users/sicko/blog/test/.vuepress/.temp/.server/app.js:24370:112)
    at Object.<anonymous> (/Users/sicko/blog/test/.vuepress/.temp/.server/app.js:24202:13)
    at t (/Users/sicko/blog/test/.vuepress/.temp/.server/app.js:20275:22)
    at Object.<anonymous> (/Users/sicko/blog/test/.vuepress/.temp/.server/app.js:24417:7)
    at t (/Users/sicko/blog/test/.vuepress/.temp/.server/app.js:20275:22)
    at /Users/sicko/blog/test/.vuepress/.temp/.server/app.js:20291:20
    at /Users/sicko/blog/test/.vuepress/.temp/.server/app.js:20292:6
    at /Users/sicko/blog/test/.vuepress/.temp/.server/app.js:20268:22`

**Comment by recoluan** [comment]
使用 vuepress@2.0.0-beta.46 和 vuepress-theme-reco@2.0.0-beta.16 试一下呢（记得清除缓存）。
