### ISSUE TITLE
vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错 错误信息如下

### ISSUE THREAD

**Issue by yangtonggui** [vuepress-reco/vuepress-theme-reco#76]
vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错 有大佬知道是解决办法吗 万分感谢
错误信息如下
error Error rendering /tag/: false
undefined
error Error rendering /timeline/: false
undefined
error Error rendering /tag/tag1/: false
undefined
error Error rendering /tag/tag2/: false
undefined
error Error rendering /tag/tag3/: false
undefined
error Error rendering /tag/tag4/: false
undefined
error Error rendering /categories/category1/: false
undefined
error Error rendering /categories/category2/: false
undefined
[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

[Vue warn]: Error in setup: “Error: must be called in setup”

found in

—>

error Error rendering /categories/: false
undefined
error Error rendering /: false
undefined
error Error rendering /blogs/category1/2018/121501.html: false
undefined
error Error rendering /blogs/category1/2019/092101.html: false
undefined
error Error rendering /blogs/category2/2016/121501.html: false
undefined
error Error rendering /blogs/category2/2017/092101.html: false
undefined
error Error rendering /docs/theme-reco/: false
undefined
error Error rendering /docs/theme-reco/api.html: false
undefined
error Error rendering /docs/theme-reco/plugin.html: false
undefined
error Error rendering /docs/theme-reco/theme.html: false
undefined
error Error rendering /blogs/other/guide.html: false
undefined
Error: must be called in setup
at useInstance (node_modules/vuepress-theme-reco/helpers/composable.js:5:17)
at setup (node_modules/vuepress-theme-reco/layouts/404.vue:24:0)
at mergedSetupFn (node_modules/@vue/composition-api/dist/vue-composition-api.esm.js:1672:88)
at invokeWithErrorHandling (D:\demo\demo3\my-blog\node_modules\vue\dist\vue.runtime.common.dev.js:3878:30)
at initSetup (D:\demo\demo3\my-blog\node_modules\vue\dist\vue.runtime.common.dev.js:2284:29)
at initState (D:\demo\demo3\my-blog\node_modules\vue\dist\vue.runtime.common.dev.js:5104:5)
at VueComponent.Vue._init (D:\demo\demo3\my-blog\node_modules\vue\dist\vue.runtime.common.dev.js:5418:9)
at new VueComponent (D:\demo\demo3\my-blog\node_modules\vue\dist\vue.runtime.common.dev.js:5553:18)
at createComponentInstanceForVnode (D:\demo\demo3\my-blog\node_modules\vue-server-renderer\build.dev.js:1979:12)
at renderComponentInner (D:\demo\demo3\my-blog\node_modules\vue-server-renderer\build.dev.js:7187:45)
at renderComponent (D:\demo\demo3\my-blog\node_modules\vue-server-renderer\build.dev.js:7164:9)
at resolve (D:\demo\demo3\my-blog\node_modules\vue-server-renderer\build.dev.js:7213:17)

**Comment by besthunterhj** [comment]
我也遇到相同的问题，让我感到非常困恼，求助各位！

**Comment by recoluan** [comment]
把环境贴一下，这样没办法定位问题

**Comment by Lucky-Ya-Q** [comment]
> 把环境贴一下，这样没办法定位问题

下载模板[vuepress-theme-reco-demo/1.x](https://github.com/vuepress-reco/vuepress-theme-reco-demo/tree/demo/1.x)
执行 `npm i` 安装依赖
执行 `npm run dev` 正常运行
执行 `npm run build` 就报这个错误
我看好几个人都遇到了这个问题，之前没事

**Comment by yangtonggui** [comment]
是新创建项目, 未修改任何地方
根据如下命令创建
#npm
$&nbsp;npm install @vuepress-reco/theme-cli -g&nbsp;$&nbsp;theme-cli init
然后npm run build 就报错了&nbsp; &nbsp;运行npm run dev 正常


相关环境 node 16.14.0&nbsp; &nbsp;theme-cli 1.0.0 vuepress 1.9.7&nbsp;









vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错

错误信息如下
















 
把环境贴一下，这样没办法定位问题

**Comment by yangtonggui** [comment]
是新创建项目, 未修改任何地方
根据如下命令创建
#npm
$ npm install @vuepress-reco/theme-cli -g 
$ theme-cli init
然后npm run build 就报错了   运行npm run dev 正常

相关环境 node 16.14.0   theme-cli 1.0.0 vuepress 1.9.7  vue  @vue/cli 5.0.6



![image](https://user-images.githubusercontent.com/44868434/177087593-6e6046c2-33bc-4648-b2cf-db189b806596.png)
![image](https://user-images.githubusercontent.com/44868434/177087638-6e88598b-b464-42e6-a701-2d61adb73460.png)


vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错
错误信息如下

![image](https://user-images.githubusercontent.com/44868434/177087702-4ff5b508-45bb-4c17-924d-13e0e8a032a0.png)
![image](https://user-images.githubusercontent.com/44868434/177087770-063ba200-7212-4cc9-b27c-13309769e70a.png)

把环境贴一下，这样没办法定位问题

**Comment by recoluan** [comment]
我这边跟进一下

**Comment by yangtonggui** [comment]
好的&nbsp; 同事把代码拉下来也是报相同错误


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuepress-reco/vuepress-theme-reco"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuepress-reco/vuepress-theme-reco] vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错 错误信息如下 (Issue #76)





 
我这边跟进一下

**Comment by wangwei1237** [comment]
我也遇到了同样的问题，6.30的时候还没问题，可以正常编译打包，但是7.2号突然出现了一样的问题。

**Comment by Lucky-Ya-Q** [comment]
> 我也遇到了同样的问题，6.30的时候还没问题，可以正常编译打包，但是7.2号突然出现了一样的问题。

是因为Vue正式发布了2.7版本的原因吗

**Comment by jokervTv** [comment]
#75 似乎是相同的问题

**Comment by QianShi-ffg** [comment]
同款问题.................重新装了一下依赖再打包就报这个错

**Comment by zuxian** [comment]
同遇到Error: must be called in setup
    at useInstance (node_modules/_vuepress-theme-reco@1.6.10@vuepress-theme-reco/helpers/composable.js:5:17)

**Comment by Kabobi** [comment]
同遇到

**Comment by recoluan** [comment]
应该是 vuepress 没有锁 vue
版本导致的，进行了兼容处理之后，又出现了 stylus 文件无法解析的错误，还没有找到解决方案。

**Comment by AriseMarcher** [comment]
Error in setup: "Error: must be called in setup"
must be called in setup
    at useInstance (composable.js?7b09:5:1)
    at setup (Layout.vue?3e79:24:1)
    at mergedSetupFn (vue-composition-api.esm.js?a6f4:1672:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:3988:1)
    at initSetup (vue.runtime.esm.js?2b0e:2382:1)
    at initState (vue.runtime.esm.js?2b0e:5255:1)
    at Vue._init (vue.runtime.esm.js?2b0e:5580:1)
    at new VueComponent (vue.runtime.esm.js?2b0e:5715:1)
    at createComponentInstanceForVnode (vue.runtime.esm.js?2b0e:2212:1)
    at init (vue.runtime.esm.js?2b0e:2074:1)

都是这个原因吗？vuepress 没有锁 vue

**Comment by AriseMarcher** [comment]
可以尝试先把 vuepress-theme-reco版本降到 1.5.7

**Comment by recoluan** [comment]
大家试一下 1.6.14

**Comment by wangwei1237** [comment]
> 可以尝试先把 vuepress-theme-reco版本降到 1.5.7

降级到1.5.7版本是可以的。

**Comment by jokervTv** [comment]
> 

最新的 1.6.14 也可以

**Comment by yangtonggui** [comment]
大佬你好&nbsp; &nbsp;侧边栏 添加属性subSidebar: "auto"&nbsp; &nbsp; &nbsp; 侧边栏会随着页面滚动并且页面会自动滚动到顶部&nbsp; &nbsp;我试着移动side-bar节点 后。如图方法后 就能正常了
问题复现地址&nbsp; http://119.3.228.178/yangtg/docs/base/css.html#%E8%AF%AD%E6%B3%95






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuepress-reco/vuepress-theme-reco"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuepress-reco/vuepress-theme-reco] [1.x] vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错 错误信息如下 (Issue #76)





 
Closed #76 as completed.

**Comment by wencwcoder** [comment]
> 同款问题.................重新装了一下依赖再打包就报这个错

我也是的，重新拉的依赖就报错了

**Comment by yangtonggui** [comment]
大佬你好&nbsp; &nbsp;侧边栏 添加属性subSidebar: "auto"&nbsp; &nbsp; &nbsp; 侧边栏会随着页面滚动并且页面会自动滚动到顶部&nbsp; &nbsp;我试着移动side-bar节点 后。如图方法后 就能正常了
问题复现地址&nbsp; http://119.3.228.178/yangtg/docs/base/css.html#%E8%AF%AD%E6%B3%95






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "vuepress-reco/vuepress-theme-reco"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuepress-reco/vuepress-theme-reco] [1.x] vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错 错误信息如下 (Issue #76)





 
Closed #76 as completed.

**Comment by yangtonggui** [comment]
你好
新创建项目, 未修改任何地方
根据如下命令创建(下载模板vuepress-theme-reco-demo/1.x&nbsp;这样也是抱相同的错误)
#npm
$&nbsp;npm install @vuepress-reco/theme-cli -g&nbsp;$&nbsp;theme-cli init
然后npm run build 就报错了&nbsp; &nbsp;运行npm run dev 正常


相关环境&nbsp;node 16.14.0&nbsp; &nbsp;theme-cli 1.0.0 vuepress 1.9.7&nbsp; &nbsp; vue&nbsp; @vue/cli 5.0.6&nbsp;









vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错

错误信息如下














------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuepress-reco/vuepress-theme-reco"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 上午9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuepress-reco/vuepress-theme-reco] vuepress-theme-reco在config.js中使用主题 “theme”: “reco” 运行正常 打包报错 错误信息如下 (Issue #76)





  
把环境贴一下，这样没办法定位问题
  
下载模板vuepress-theme-reco-demo/1.x
 执行 npm i 安装依赖
 执行 npm run dev 正常运行
 执行 npm run build 就报这个错误
 我看好几个人都遇到了这个问题，之前没事
