### ISSUE TITLE
2.x 项目部署报错

### ISSUE THREAD

**Issue by lvr1997** [vuepress-reco/vuepress-theme-reco#83]
Node环境：14.18.2 操作系统：windows10
我是使用 theme-cli 1.0.7 构建的项目
项目依赖包版本  "vuepress": "2.0.0-beta.48",  "vuepress-theme-reco": "2.0.0-beta.20"

执行yarn build 报错如下，但可以打包
✔ Compiling with vite - done
⠋ Rendering pages⠋ Rendering pages /ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
⠙ Rendering pagesReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
⠙ Rendering pages /blogs/frontEnd/vue/01-vuejichuhuigu.htmlReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:8802:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at E:\myblog2\.vuepress\.temp\.server\app.js:7459:28
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
⠹ Rendering pagesReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at _sfc_ssrRender$7 (E:\myblog2\.vuepress\.temp\.server\app.js:7912:24)
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at _sfc_ssrRender$7 (E:\myblog2\.vuepress\.temp\.server\app.js:7912:24)
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at _sfc_ssrRender$7 (E:\myblog2\.vuepress\.temp\.server\app.js:7912:24)
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at _sfc_ssrRender$7 (E:\myblog2\.vuepress\.temp\.server\app.js:7912:24)
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at _sfc_ssrRender$7 (E:\myblog2\.vuepress\.temp\.server\app.js:7912:24)
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
ReferenceError: sessionStorage is not defined
    at usePassword (E:\myblog2\.vuepress\.temp\.server\app.js:7387:33)
    at setup (E:\myblog2\.vuepress\.temp\.server\app.js:7410:9)
    at _sfc_main$j.setup (E:\myblog2\.vuepress\.temp\.server\app.js:7447:25)
    at callWithErrorHandling (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5789:29)
    at setupComponent (E:\myblog2\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at Object.ssrRenderComponent (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:605:12)
    at _sfc_ssrRender$7 (E:\myblog2\.vuepress\.temp\.server\app.js:7912:24)
    at renderComponentSubTree (E:\myblog2\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:250:13)
[Vue warn]: Component index.vue is missing template or render function.
✔ Rendering pages - done

上传到github pages后，浏览器打开之后只显示一个首页，其余的内容都没有显示
我的部署访问地址：https://lvr1997.github.io/

f12控制台报错如下：
![image](https://user-images.githubusercontent.com/37863122/178451467-34911d43-f8dd-4154-a406-1e554f74e4a8.png)
![image](https://user-images.githubusercontent.com/37863122/178451569-25667bed-be19-47b2-b936-6c7707939df0.png)

望解决一下！谢谢

**Comment by Burial0268** [comment]
我也遇到了这个问题，你解决了吗？怎么解决的，求教

**Comment by HanamakiX** [comment]
我解决了，方法：提升版本修改package.json部分改成：   
"dependencies": {
    "vuepress": "2.0.0-beta.48",
    "vuepress-theme-reco": "2.0.0-beta.21"
  }

然后删除node_modules和yarn.lock和.vuepress下的（.temp和.cache）；
然后重新安装：yarn install,
然后编译：yarn build,
然后配置nginx，访问，我的成功样例截图如下：
![1657854807315](https://user-images.githubusercontent.com/93114589/179142696-4f060bdc-0497-427d-bb67-71d3bfbebc01.png)

**Comment by jinhan52** [comment]
@HanamakiX 非常感谢，我解决了

**Comment by xp-bear** [comment]
我也来尝试一下

**Comment by shkmzzh** [comment]
@HanamakiX @lvr1997 你好，我npm run build时js和css的路径都少一个 . 请问你们是怎么配置的呢
