### ISSUE TITLE
2.x项目build错误，提示 Error: usePageFrontmatter() is called without provider.

### ISSUE THREAD

**Issue by Burial0268** [vuepress-reco/vuepress-theme-reco#88]
如题，我在执行yarn build的时候，提示：
⠴ Compiling with vite
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✔ Compiling with vite - done
⠋ Rendering pages⠋ Rendering pages /Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠙ Rendering pagesError: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠙ Rendering pages /docs/theme-reco/api.htmlError: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠹ Rendering pagesError: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠹ Rendering pages /blogs/category1/2018/121501.htmlError: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠸ Rendering pagesError: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠸ Rendering pages /404.htmlError: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠼ Rendering pagesError: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠼ Rendering pages /tags/tag4/1/Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
Error: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.
⠴ Rendering pagesError: usePageFrontmatter() is called without provider.
    at usePageFrontmatter (/www/wwwroot/service/.vuepress/.temp/.server/app.js:4989:11)
    at applyClientSetup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5223:23)
    at Object.setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5583:5)
    at setup (/www/wwwroot/service/.vuepress/.temp/.server/app.js:5726:59)
    at callWithErrorHandling (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5789:29)
    at setupComponent (/www/wwwroot/service/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5770:11)
    at renderComponentVNode (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
    at renderToString (/www/wwwroot/service/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:443:26)
    at renderPage (/www/wwwroot/service/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:21:32)
[Vue warn]: Component VuepressApp is missing template or render function.

构建是能构建，但控制台报错：
app.1d43407d.js:1 
        
       Error: usePageFrontmatter() is called without provider.
    at O7 (app.1d43407d.js:389:11531)
    at Y7 (app.1d43407d.js:389:14214)
    at Object.setup (app.1d43407d.js:389:2300052)
    at setup (app.1d43407d.js:389:2304518)
    at J2 (app.1d43407d.js:1:15089)
    at jc (app.1d43407d.js:1:55591)
    at Ac (app.1d43407d.js:1:55376)
    at O1 (app.1d43407d.js:1:44883)
    at g (app.1d43407d.js:1:39105)
    at v (app.1d43407d.js:1:38239)

求解决

**Comment by recoluan** [comment]
Try to update  reco theme to latest version 1.6.14.

**Comment by Burial0268** [comment]
> Try to update reco theme to latest version 1.6.14.

这个我解决了，但是他会报 #89 的错误

**Comment by recoluan** [comment]
It does not affect the normal use of compiled files, can be temporarily ignored, later repair.

**Comment by hanhanhan1124** [comment]
> > Try to update reco theme to latest version 1.6.14.
> 
> 这个我解决了，但是他会报 #89 的错误

请问怎么解决的呢

**Comment by hanhanhan1124** [comment]
> 



> > Try to update reco theme to latest version 1.6.14.
> 
> 这个我解决了，但是他会报 #89 的错误

求教大佬

**Comment by Burial0268** [comment]
> 

这个issue挺早的了，现在我也忘了当时是怎么解决的，抱歉，帮不了你
