### ISSUE TITLE
[1.x] 莫名出现TypeError: Cannot read properties of null (reading 'proxy')错误

### ISSUE THREAD

**Issue by Arielwyy** [vuepress-reco/vuepress-theme-reco#91]
**Describe the bug**
推送到github action构建，和本地yarn run build构建都会出现这个错，blog已经稳定运行了几个月了，今天发现出了这个错，另外一份其他人的blog也出现了这个错误
TypeError: Cannot read properties of null (reading 'proxy')
    at setup (node_modules/vuepress-theme-reco/layouts/404.vue:12:42)
    at mergedSetupFn (node_modules/@vue/composition-api/dist/vue-composition-api.mjs:2165:78)
    at invokeWithErrorHandling (/home/runner/work/blog/blog/node_modules/vue/dist/vue.runtime.common.dev.js:2869:30)
    at initSetup (/home/runner/work/blog/blog/node_modules/vue/dist/vue.runtime.common.dev.js:2318:29)
    at initState (/home/runner/work/blog/blog/node_modules/vue/dist/vue.runtime.common.dev.js:5207:5)
    at VueComponent.Vue._init (/home/runner/work/blog/blog/node_modules/vue/dist/vue.runtime.common.dev.js:5521:9)
    at new VueComponent (/home/runner/work/blog/blog/node_modules/vue/dist/vue.runtime.common.dev.js:5656:18)
    at createComponentInstanceForVnode (/home/runner/work/blog/blog/node_modules/vue-server-renderer/build.dev.js:2532:12)
    at renderComponentInner (/home/runner/work/blog/blog/node_modules/vue-server-renderer/build.dev.js:7190:45)
    at renderComponent (/home/runner/work/blog/blog/node_modules/vue-server-renderer/build.dev.js:7167:9)
    at resolve (/home/runner/work/blog/blog/node_modules/vue-server-renderer/build.dev.js:7216:17)
error Command failed with exit code 1.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44137597/179348826-12b2dac2-d834-4199-aa68-c78101644918.png)
![image](https://user-images.githubusercontent.com/44137597/179348842-b50fbdf9-5f64-4cd5-91b8-737b893cb5ce.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - vuepress 1.8.2
 - vuepress-theme-reco 1.6.6

**Comment by recoluan** [comment]
Try to upgrade the reco theme to the latest version 1.6.14 .

**Comment by wencwcoder** [comment]
> 

升级后出现该问题 -- injection "Symbol(showModuleSymbol)" not found.

**Comment by wencwcoder** [comment]
> Try to upgrade the reco theme to the latest version 1.6.14 .

升级后出现该问题 -- injection "Symbol(showModuleSymbol)" not found.
